### ISSUE TITLE
analytics

### ISSUE THREAD

**Issue by evanwill** [drodz11/colors-of-ozu#1]
@drodz11 I just noticed that your site is using my personal google analytics id (which was in the default CollectionBuilder template as an example value). 
In your ["_config.yml"](https://github.com/drodz11/colors-of-ozu/blob/master/_config.yml) file, you should comment out lines 40 and 41 by putting a `#` in front of  `google-analytics-id` and `google-cse-id` to turn them off. Or you could [set up your own analytics](https://collectionbuilder.github.io/cb-docs/docs/advanced/analytics/) and replace the `google-analytics-id`.

I really enjoyed exploring your project!

**Comment by drodz11** [comment]
Thanks, Evan! Your GA ID has been removed from _config.yml. Glad you enjoyed taking a look at it!
